{% set name = "Pyfhel" %}
{% set version = "3.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ibarrond/Pyfhel/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 37825ce03a54e7ca9e2d39f6fd4bf19e4d58ec28cd856fe4d7a0fef4cefed5bf
  patches:
    - patches/0001-no-system-include.patch
    - patches/0002-unvendor-seal.patch

build:
  number: 0
  # osx gives a python Abort trap: 6 on tests, for more info
  # have a look at:
  # https://github.com/AnacondaRecipes/pyfhel-feedstock/pull/1
  # win builds, but can't import Pyfhel, something is missing.
  # On the next update it should be investigated and completed.
  skip: true  # [win]
  missing_dso_whitelist:
    - '*/ld64.so.1'          # [s390x]
    - '*/libc++.1.dylib'     # [osx]
    - '*/libzstd.1.dylib'    # [osx]
    - '*/libz.1.dylib'       # [osx]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake >=3.15
    - patch     # [not win]
    - m2-patch  # [win]
  host:
    - python
    - pip
    - setuptools
    - wheel
    - cython >=3.0.0
    - numpy {{ numpy }}
    - toml >=0.1
    - seal
    - llvm-openmp   # [osx]
    - libgomp       # [linux]
    - zlib {{ zlib }}
    - zstd {{ zstd }}
  run:
    - numpy >=1.21
    - python

test:
  imports:
    - Pyfhel
    - Pyfhel.utils
  requires:
    - pip
    - pytest
  source_files:
    - Pyfhel/test
    - examples
    - pyproject.toml
  commands:
    - pip check
    - pytest -v .

about:
  home: https://pyfhel.readthedocs.io
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: Python for Homomorphic Encryption Libraries
  description: |
    Python library for Addition, Subtraction, Multiplication and
    Scalar Product over encrypted integers (BFV/BGV schemes) and
    approximated floating point values (CKKS scheme). This library
    acts as an optimized Python API for C++ Homomorphic Encryption
    libraries.
  doc_url: https://pyfhel.readthedocs.io
  dev_url: https://github.com/ibarrond/Pyfhel

extra:
  recipe-maintainers:
    - lorepirri
